version: "3.8"
services:
  app:
    build: .
    env_file:
      - .env
    ports:
      - "8000:8000"
      - "5432:5432" # can be removed later
    depends_on:
      - db
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
